'use client';

/**
 * ============================================================================
 * NEXUS PRIME - INSIGHT FEED
 * ============================================================================
 * 
 * Feed of insights generated by agents:
 * - Real-time insight display
 * - Expandable cards
 * - Action shortcuts
 * 
 * @module nexus/prime/ui/InsightFeed
 * @version 1.0.0
 */

import React, { useState } from 'react';
import { Insight } from '../core/types';

// ============================================================================
// TYPES
// ============================================================================

interface InsightFeedProps {
  insights: Insight[];
  onInsightAction?: (insight: Insight, action: string) => void;
  onDismiss?: (insight: Insight) => void;
  maxVisible?: number;
  className?: string;
}

// ============================================================================
// COMPONENT
// ============================================================================

export function InsightFeed({
  insights,
  onInsightAction,
  onDismiss,
  maxVisible = 10,
  className = '',
}: InsightFeedProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [filter, setFilter] = useState<Insight['level'] | 'all'>('all');

  // Filter insights
  const filteredInsights = insights
    .filter(i => filter === 'all' || i.level === filter)
    .slice(0, maxVisible);

  // Count by level
  const counts = {
    all: insights.length,
    critical: insights.filter(i => i.level === 'critical').length,
    warning: insights.filter(i => i.level === 'warning').length,
    info: insights.filter(i => i.level === 'info').length,
    success: insights.filter(i => i.level === 'success').length,
  };

  return (
    <div className={`flex flex-col ${className}`}>
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-semibold">Insights</h3>
        <div className="flex items-center gap-1">
          {(['all', 'critical', 'warning', 'info', 'success'] as const).map(level => (
            <button
              key={level}
              onClick={() => setFilter(level)}
              className={`px-2 py-1 text-xs rounded transition-colors ${
                filter === level
                  ? 'bg-primary text-primary-foreground'
                  : 'bg-muted hover:bg-muted/80'
              }`}
            >
              {level} ({counts[level]})
            </button>
          ))}
        </div>
      </div>

      {/* Insight List */}
      {filteredInsights.length === 0 ? (
        <div className="text-center py-8 text-muted-foreground">
          <p className="text-sm">No insights to display</p>
          <p className="text-xs mt-1">Insights will appear as NEXUS analyzes your data</p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredInsights.map(insight => (
            <InsightCard
              key={insight.id}
              insight={insight}
              isExpanded={expandedId === insight.id}
              onToggle={() => setExpandedId(expandedId === insight.id ? null : insight.id)}
              onAction={(action) => onInsightAction?.(insight, action)}
              onDismiss={() => onDismiss?.(insight)}
            />
          ))}
        </div>
      )}

      {/* Show More */}
      {insights.length > maxVisible && (
        <button className="mt-4 text-sm text-muted-foreground hover:text-foreground">
          Show {insights.length - maxVisible} more insights
        </button>
      )}
    </div>
  );
}

// ============================================================================
// INSIGHT CARD
// ============================================================================

function InsightCard({
  insight,
  isExpanded,
  onToggle,
  onAction,
  onDismiss,
}: {
  insight: Insight;
  isExpanded: boolean;
  onToggle: () => void;
  onAction: (action: string) => void;
  onDismiss: () => void;
}) {
  const getLevelIcon = (level: Insight['level']) => {
    switch (level) {
      case 'critical':
        return '🔴';
      case 'warning':
        return '🟡';
      case 'success':
        return '🟢';
      default:
        return '🔵';
    }
  };

  const getLevelStyles = (level: Insight['level']) => {
    switch (level) {
      case 'critical':
        return 'border-l-4 border-l-destructive bg-destructive/5';
      case 'warning':
        return 'border-l-4 border-l-yellow-500 bg-yellow-500/5';
      case 'success':
        return 'border-l-4 border-l-green-500 bg-green-500/5';
      default:
        return 'border-l-4 border-l-blue-500 bg-blue-500/5';
    }
  };

  const getTypeIcon = (type: Insight['type']) => {
    switch (type) {
      case 'trend':
        return '📈';
      case 'anomaly':
        return '⚠️';
      case 'pattern':
        return '🔄';
      case 'prediction':
        return '🔮';
      case 'correlation':
        return '🔗';
      case 'improvement':
        return '💡';
      case 'optimization':
        return '⚡';
      default:
        return '📊';
    }
  };

  return (
    <div
      className={`rounded-lg overflow-hidden transition-all ${getLevelStyles(insight.level)}`}
    >
      {/* Header */}
      <div
        onClick={onToggle}
        className="flex items-start gap-3 p-4 cursor-pointer hover:bg-black/5 dark:hover:bg-white/5"
      >
        <div className="text-lg">{getLevelIcon(insight.level)}</div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="text-sm">{getTypeIcon(insight.type)}</span>
            <span className="font-medium text-sm">{insight.title}</span>
          </div>
          <p className="text-xs text-muted-foreground mt-1 line-clamp-2">
            {insight.description}
          </p>
          <div className="flex items-center gap-3 mt-2 text-[10px] text-muted-foreground">
            <span>{insight.source}</span>
            <span>•</span>
            <span>{Math.round(insight.confidence * 100)}% confidence</span>
            <span>•</span>
            <span>{formatTimeAgo(insight.timestamp)}</span>
          </div>
        </div>
        <button
          onClick={(e) => {
            e.stopPropagation();
            onDismiss();
          }}
          className="p-1 hover:bg-black/10 dark:hover:bg-white/10 rounded"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </button>
      </div>

      {/* Expanded Content */}
      {isExpanded && (
        <div className="px-4 pb-4 pt-0 border-t border-black/5 dark:border-white/5">
          {/* Data */}
          {insight.data && (
            <div className="mt-3">
              <div className="text-xs font-medium text-muted-foreground mb-1">Data</div>
              <pre className="text-xs bg-muted p-2 rounded overflow-x-auto">
                {JSON.stringify(insight.data, null, 2)}
              </pre>
            </div>
          )}

          {/* Suggestions */}
          {insight.suggestions && insight.suggestions.length > 0 && (
            <div className="mt-3">
              <div className="text-xs font-medium text-muted-foreground mb-1">Suggestions</div>
              <ul className="space-y-1">
                {insight.suggestions.map((suggestion, index) => (
                  <li key={index} className="text-xs flex items-center gap-2">
                    <span className="text-muted-foreground">→</span>
                    {suggestion}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Actions */}
          <div className="flex items-center gap-2 mt-4">
            <button
              onClick={() => onAction('explore')}
              className="px-3 py-1.5 text-xs bg-primary text-primary-foreground rounded hover:opacity-90"
            >
              Explore
            </button>
            <button
              onClick={() => onAction('automate')}
              className="px-3 py-1.5 text-xs bg-muted text-foreground rounded hover:bg-muted/80"
            >
              Create Automation
            </button>
            <button
              onClick={() => onAction('share')}
              className="px-3 py-1.5 text-xs bg-muted text-foreground rounded hover:bg-muted/80"
            >
              Share
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

// ============================================================================
// HELPERS
// ============================================================================

function formatTimeAgo(timestamp: number): string {
  const seconds = Math.floor((Date.now() - timestamp) / 1000);

  if (seconds < 60) return 'just now';
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  return `${Math.floor(seconds / 86400)}d ago`;
}

export default InsightFeed;

